import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Lora, Pacifico, Playfair_Display } from '@next/font/google';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


const lora = Lora({ subsets: ['latin'], weight: ['400', '700'], style: ['normal', 'italic'] });
const pacifico = Pacifico({ subsets: ['latin'], weight: '400' });
const playfairDisplay = Playfair_Display({ subsets: ['latin'], weight: ['400', '900'], style: ['normal', 'italic']

 });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export { lora, pacifico, playfairDisplay }; // Export des polices pour les utiliser dans d'autres fichiers
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${lora.className} ${playfairDisplay.className}`}
      >
    
        {children}
      </body>
    </html>
  );
}
